# run: conda env create --file environment.yml
name: whisper
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.1.2
  - torchaudio=2.1.2
  - pytorch-cuda=11.8
  - pip=23.3.2
  - pip:
    - transformers==4.36.1
    - accelerate==0.26.1
    - datasets==2.16.1
    # - flash-attn==2.5.0
    - packaging==23.2
    - ninja==1.11.1.1
    - nltk==3.8.1
    - jiwer==3.0.3
    #- num2words==0.5.2
    - mutagen==1.46.0
    - tqdm==4.64.1
    - pyarrow==15.0.0
    - yt-dlp==2023.10.13
    - webvtt-py==0.4.6
    - lingua-language-detector==2.0.2
    - soundfile==0.12.1
